services:
  ollama:
    image: ollama/ollama
    container_name: ollamaa
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]